name = "hhapi"
main = "src/index.ts"
compatibility_date = "2026-06-01"
account_id = "b5cdaad4db136b796354280697e0ceb9"

[vars]
DATA_VERSION = "2026-06"

[[r2_buckets]]
binding = "GRAPH"
bucket_name = "hhapi-graph"

[[d1_databases]]
binding = "GEOCODE"
database_name = "hhapi-geocode"
database_id = "026b910d-9352-4c5e-974b-674a3f1b0510"

[[kv_namespaces]]
binding = "CACHE"
id = "f36df580b639463b85b337a0b2e9ab20"

[[routes]]
pattern = "hhapi.propspress.com"
custom_domain = true

[limits]
cpu_ms = 30000
